import Appbar from "../src/components/Appbar";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../src/theme/ThemeProvider";
import Head from "next/head";
import AuthContext from "../src/context/authContext";
import { useEffect, useState } from "react";
import verify from "../src/lib/verify";
import "../src/Global.css";

function MyApp({ Component, pageProps }) {
  const [auth, setAuth] = useState({});

  useEffect(() => {
    const token = window.localStorage.getItem("token");
    const verifyInterval = setInterval(async () => {
      if (token != undefined) {
        const verified = await verify(token);
        if (!verified?.data?.user_id) {
          setAuth({});
        } else {
          const data = verified.data;
          setAuth({ id: data.user_id });
        }
      }
    }, 1000);
    return () => clearInterval(verifyInterval);
  }, [auth]);

  return (
    <>
      <ThemeProvider theme={theme}>
        <AuthContext.Provider value={{ auth, setAuth }}>
          <Head>
            <title>Woof & Co.</title>
            <meta name="description" content="Generated by anti bird gang" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Appbar />
          <Component {...pageProps} />
        </AuthContext.Provider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
